### ISSUE TITLE
1ms lag on bottom row buttons

### ISSUE THREAD

**Issue by ltlnx** [hiroshiyui/GuilelessBopomofo#12]
Hello,
it seems like the bottom-most row of buttons don't use the haptic feedback, as they are not affected by changing the "vibrate strength" setting, and they have a ~1ms lag.
By the way I mean this row:
![Screenshot_20210605-152311_Iceraven_01](https://user-images.githubusercontent.com/52026741/120883860-3bce0300-c612-11eb-93fb-d266d4bf2c07.png)
Both Chinese and English keyboards are affected.

**Comment by hiroshiyui** [comment]
It's by design that haptic feedback strength of modifier keys and special keys are different to character keys, thus I can aware that I have touched such keys.

And... I am curious about the "1ms" you said, a ms is 1/1000 second, am I misunderstand it? The "lag" effect you feel might caused by the heavy haptic feedback strength applied to these keys.

**Comment by ltlnx** [comment]
Uh sorry I mean about 1/10 second. The number is probably not accurate, but on my side it's noticeable.

**Comment by hiroshiyui** [comment]
@ltlnx You may give the new release a try, I've tested it on my Xperia Z3 Compact, and I can just assure the bottom buttons are working, but I don't know if it solves your issue or not. (If the issue still occurs, how about give me a screen-recording, which may brings me more ideas?)

**Comment by ltlnx** [comment]
Yes, the lag is fixed, and typing haven't been more fluid. Thank you!
